<a href="https://colab.research.google.com/github/SaiSriVidyadhari/SaiSriVidyadhari/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from numpy.linalg import eig,multi_dot
A=np.array([[2,-3,0],
            [2,-5,0],
            [0,0,3]])
w,v=eig(A)
print("Eigen Value:",w)
print("Eigen Vector:",v)

Eigen Value: [ 1. -4.  3.]
Eigen Vector: [[0.9486833  0.4472136  0.        ]
 [0.31622777 0.89442719 0.        ]
 [0.         0.         1.        ]]


In [ ]:
from numpy.linalg.linalg import eigvals
x=eigvals(A)
print(x)

[ 1. -4.  3.]


In [ ]:
A=np.array([[2,-3,0],
            [2,-5,0],
            [0,0,3]])
B=np.array([[2,-6,3],
            [8,-12,7],
            [5,9,3]])

In [ ]:
#from numpy.linalg import vdot
np.dot(A,B)

array([[-20,  24, -15],
       [-36,  48, -29],
       [ 15,  27,   9]])

In [ ]:
np.inner(A,B)

array([[ 22,  52, -17],
       [ 34,  76, -35],
       [  9,  21,   9]])

In [ ]:
np.outer(A,B)

array([[  4, -12,   6,  16, -24,  14,  10,  18,   6],
       [ -6,  18,  -9, -24,  36, -21, -15, -27,  -9],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  4, -12,   6,  16, -24,  14,  10,  18,   6],
       [-10,  30, -15, -40,  60, -35, -25, -45, -15],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  6, -18,   9,  24, -36,  21,  15,  27,   9]])

In [ ]:
np.vdot(A,B)

107

In [ ]:
np.linalg.matrix_power(A,2)

array([[-2,  9,  0],
       [-6, 19,  0],
       [ 0,  0,  9]])

In [ ]:
np.linalg.eig(A)

(array([ 1., -4.,  3.]), array([[0.9486833 , 0.4472136 , 0.        ],
        [0.31622777, 0.89442719, 0.        ],
        [0.        , 0.        , 1.        ]]))

In [ ]:
np.linalg.eig(B)

(array([  7.2038972 ,  -1.43500422, -12.76889298]),
 array([[-0.09723188, -0.66065842, -0.4080884 ],
        [-0.37634988, -0.00288686, -0.73115332],
        [-0.92136134,  0.7506811 ,  0.54669798]]))

In [ ]:
np.linalg.det(B)

131.99999999999997

In [ ]:
np.linalg.matrix_rank(A)

3

In [ ]:
np.linalg.solve(A,B)

array([[-3.5       ,  1.5       , -1.5       ],
       [-3.        ,  3.        , -2.        ],
       [ 1.66666667,  3.        ,  1.        ]])

In [ ]:
np.linalg.inv(A)

array([[ 1.25      , -0.75      ,  0.        ],
       [ 0.5       , -0.5       , -0.        ],
       [ 0.        ,  0.        ,  0.33333333]])

In [ ]:
np.trace(A)

0